### ISSUE TITLE
默认定位不精准

### ISSUE THREAD

**Issue by adamp4** [hocgin/chrome-extension-weather#36]
你好，地址在浙江杭州桐庐，默认定位只能在杭州，建议精确到县
你开发的插件非常好用，谢谢，工作愉快

**Comment by hocgin** [comment]
> 你好，地址在浙江杭州桐庐，默认定位只能在杭州，建议精确到县 你开发的插件非常好用，谢谢，工作愉快

@adamp4 自动定位是精确到经纬度的哈，只是展示的是市。

**Comment by NewYao** [comment]
低温有时候会显示错误   N/A°     
![image](https://user-images.githubusercontent.com/39934038/147738758-cbf0063b-e533-4438-9b19-55bc42208708.png)

**Comment by hocgin** [comment]
> 低温有时候会显示错误 N/A°
> ![image](https://user-images.githubusercontent.com/39934038/147738758-cbf0063b-e533-4438-9b19-55bc42208708.png)

👌安排

**Comment by hocgin** [comment]
3.1.9 修复了，正在审核。
